name: Upload yaml2resume to PyPI
on: 
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip3 install wheel
    - name: Build package
      run: python3 setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: "${{ secrets.PYPI_API_TOKEN }}"